### ISSUE TITLE
Panic using 0.5.1 in rustfmt: Invalid #[new] attribute, expected #[new(..)]

### ISSUE THREAD

**Issue by topecongiro** [nrc/derive-new#31]
I tried to use `#[derive(new)]` on `ArmWrapper` in [this PR](https://github.com/rust-lang-nursery/rustfmt/pull/2512). Unfortunately I got the following error:
```
   Compiling rustfmt-nightly v0.4.0 (file:///home/topecongiro/workspace/rustfmt)
error: proc-macro derive panicked
    --> src/expr.rs:1264:10
     |
1264 | #[derive(new)]
     |          ^^^
     |
     = help: message: Invalid #[new] attribute, expected #[new(..)]

error: Could not compile `rustfmt-nightly`.

To learn more, run the command again with --verbose.
```

A difinition of `ArmWrapper`:

```rust
/// A simple wrapper type against ast::Arm. Used inside write_list().
#[derive(new)]
struct ArmWrapper<'a> {
    pub arm: &'a ast::Arm,
    /// True if the arm is the last one in match expression. Used to decide on whether we should add
    /// trailing comma to the match arm when `config.trailing_comma() == Never`.
    pub is_last: bool,
    /// Holds a byte position of `|` at the beginning of the arm pattern, if available.
    pub beginning_vert: Option<BytePos>,
}
```

I am using `derive-new 0.5.1`.

**Comment by bjgill** [comment]
I've seen this as well. I'm getting an identical error message when running `cargo +nightly build`.

I strongly suspect this must be a regression in a recent nightly. I'll have a look at raising an issue with Rustc.

**Comment by bjgill** [comment]
Actually - I can repro this in the nightly from the 18th of March, but not the current one, so I suspect this may be a regression already fixed in nightly. 

@topecongiro - what version of rustc are you using? Does updating to `rustc 1.26.0-nightly (2789b067d 2018-03-06)` help?

**Comment by topecongiro** [comment]
@bjgill Thank you for the suggestion. Unfortunately the issue still persists even when I use `rustc 1.26.0-nightly (2789b067d 2018-03-06)`.
